yarnPath: .yarn/releases/yarn-3.2.2.cjs

npmScopes:
  consensus-labs:
    npmRegistryServer: https://gitlab.com/api/v4/packages/npm/

logFilters:
  - code: YN0002
    level: error

nodeLinker: node-modules
enableGlobalCache: true
