packages:
  - libs/*

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  less: true
  lmdb: true
  msgpackr-extract: true
  nx: true

catalog:
  '@angular/build': ^22.2.0
  '@angular/cli': ^22.2.0
  '@angular/compiler-cli': ^22.2.0
  '@angular/core': ^22.2.0
  '@angular/common': ^22.2.0
  '@angular/router': ^22.2.0
  '@angular/material': ^22.2.0
  '@angular/forms': ^22.2.0
  '@angular/cdk': ^22.2.0
  '@angular/animations': ^22.2.0
  "@angular/platform-browser": ^22.2.0
  "@angular/service-worker": ^22.2.0
  'ng-packagr': ^22.2.0

minimumReleaseAgeExclude:
  - '@juulsgaard/ngx-forms-core@22.0.0 || 22.0.2'

nodeLinker: isolated
